With docker
alejo9226/CondoAppmin-BackEnd pull request #13
Opened 2020-12-09 05:29 UTC by dafegosa

Add Dockerfile
Connect with cloudinary

![image](https://user-images.githubusercontent.com/17477347/101588983-8ea56580-39b5-11eb-9241-3bae8586561d.png)

2020-12-09 11:03 UTC, simonhoyos commented
Este PR está apuntando a master

2020-12-09 15:36 UTC, dafegosa commented
@simonhoyos  apuntando a development

2020-12-09 18:41 UTC, simonhoyos requested changes
Recuerda que los PRs deben ser más especificos. Según entiendo por el título del PR es para agregar Docker pero veo cambios de auth de cloudinary y en muchos archivos

2020-12-09 18:41 UTC, simonhoyos commented on yarn-error.log
> -  /usr/local/bin/node /Users/alejandroalfaro/.npm-global/bin/yarn init
Puedes borrar este archivo completo y agregarlo al gitignore

2020-12-09 19:48 UTC, dafegosa commented
La rama en que se trabajó se llama Whit-docker. En esta se creó el archivo Dockerfile.
Adicional, se hizo la conexión con Cloudinary.  En el front hacemos uso de CKEditor y al cargar una imágen en este editor usamos CKfinder para que reconozca el archivo y lo envía al back. Acá en el Back usamos Multiparty y, como se muestra en la imágen, enciamos el archivo a Cloudinary. La url de la imágen la enviamos de respuesta al front para que quede dentro del body del CKEditor.

2020-12-10 13:27 UTC, simonhoyos approved these changes

2020-12-10 16:10 UTC, merged