Fix condo route
alejo9226/CondoAppmin-BackEnd pull request #14
Opened 2020-12-11 23:50 UTC by alejo9226

### Fix condo affected routes

Fixed condo affected routes for more transparency with FE

<img width="1020" alt="Screen Shot 2020-12-11 at 18 50 23" src="https://user-images.githubusercontent.com/20896104/101965176-bbd65b80-3be1-11eb-999d-7f61c8e6fa86.png">

2020-12-12 17:42 UTC, simonhoyos requested changes

2020-12-12 17:42 UTC, simonhoyos commented on src/controllers/condo.controller.js
> +const { deleteAll } = require("./message.controller");
Para que es este deleteAll? No ví si se estaba usando

2020-12-12 17:42 UTC, simonhoyos commented on src/controllers/ticket.controller.js
> +      if (Object.keys(req.query).length > 0) {
Que pasa si llega un query pero el query no es read?

2020-12-12 19:03 UTC, alejo9226 commented on src/controllers/condo.controller.js
> +const { deleteAll } = require("./message.controller");
Es que creo al crear ese metodo para borrar todos los condos como ya tenia uno igual en messages lo importó, pero ya lo borro

2020-12-12 19:37 UTC, alejo9226 commented on src/controllers/ticket.controller.js
> +      if (Object.keys(req.query).length > 0) {
Ya arregle para que solo funcione cuando llegue un query con el key read si es que llega un query, sino crea un error

2020-12-13 12:06 UTC, simonhoyos approved these changes

2020-12-13 15:25 UTC, merged