Subtickets
alejo9226/CondoAppmin-BackEnd pull request #16
Opened 2020-12-17 04:06 UTC by dafegosa

Add subTicket schema.

subTicket route:
![image](https://user-images.githubusercontent.com/17477347/102442708-03e6eb00-3ff3-11eb-9d8d-3c3e9641ef47.png)

subTicket controller:
![image](https://user-images.githubusercontent.com/17477347/102442780-3264c600-3ff3-11eb-96c0-c407ceb9c13a.png)

Add new key into tickets contoller.

2020-12-17 13:28 UTC, simonhoyos requested changes

2020-12-17 13:28 UTC, simonhoyos commented on src/controllers/subTicket.controller.js
> +  // async show(req, res) {
Borrar el código comentado

2020-12-17 13:28 UTC, simonhoyos commented on src/models/resident.model.js
> +    // type: Schema.Types.ObjectId,
borrar los comentarios

2020-12-17 13:28 UTC, simonhoyos commented on src/routes/subTicket.js
> +// router.route('/').get(auth, ticketController.list)
Borrar comentarios. El código comentado también se conoce como código muerto, este código hace que se más difícil mantener la base del código en el mediano y largo plazo

2020-12-18 11:22 UTC, simonhoyos requested changes

2020-12-18 11:22 UTC, simonhoyos commented on src/controllers/subTicket.controller.js
> +const { show } = require('./unit.controller')
Alguna razón para traer este método? No veo que se este usando en este controlador

2020-12-18 15:37 UTC, dafegosa commented on src/controllers/subTicket.controller.js
> +const { show } = require('./unit.controller')
Ninguna. ¡Modificado!

2020-12-18 18:35 UTC, simonhoyos approved these changes

2020-12-29 20:49 UTC, merged