Ticket routes
alejo9226/CondoAppmin-BackEnd pull request #6
Opened 2020-11-24 17:06 UTC by dafegosa

Add condo, unit and ticket route

![image](https://user-images.githubusercontent.com/17477347/100127783-7a0d8d00-2e4d-11eb-8ba1-b65afe2c1eeb.png)

2020-11-24 19:09 UTC, simonhoyos commented
Este PR incluye cambios duplicados de otros PRs. Al crear la rama se hizo desde development? hiciste pull de development antes de crear la rama?

Para actualizar lo cambios haz pull de development desde tu rama local

2020-11-25 16:49 UTC, dafegosa commented
Le hice pull desde development y solucioné varios conflictos que habían.

2020-11-25 18:29 UTC, simonhoyos requested changes

2020-11-25 18:29 UTC, simonhoyos commented on .env
>  CONNECTION_STRING=mongodb+srv://daniel:SqouHN0xqnliPsEN@cluster0.3smrd.mongodb.net/condo?retryWrites=true&w=majority
Corre el comando `git rm --cached .env` para remover este archivo por completo del git

2020-11-25 18:29 UTC, simonhoyos commented on src/controllers/admin.controller.js
> +const dotenv = require("dotenv");
Si ya se está ejecutando dotenv desde el server no es necesario requerirlo en cada archivo

2020-11-25 22:02 UTC, simonhoyos approved these changes

2020-11-25 22:06 UTC, alejo9226 commented on src/controllers/admin.controller.js
> +        .json({ message: "admins found", name: admin.name, id: admin._id });
Hay que configurar para que no te ponga los punto y comas por defecto

2020-11-25 22:08 UTC, alejo9226 approved these changes
Las comillas dobles y los punto y comas hay que configurar para que no queden por defecto

2020-11-25 22:16 UTC, merged